-- DropForeignKey
ALTER TABLE "RVM" DROP CONSTRAINT "RVM_apiKeyId_fkey";

-- AlterTable
ALTER TABLE "RVM" ALTER COLUMN "apiKeyId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "RVM" ADD CONSTRAINT "RVM_apiKeyId_fkey" FOREIGN KEY ("apiKeyId") REFERENCES "ApiKey"("id") ON DELETE SET NULL ON UPDATE CASCADE;
